language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - "pip install ."
 - "pip install pytest"
 - "pip install coveralls"
 # Coveralls 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip install coverage==3.7.1; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then pip install coverage; fi
script: coverage run setup.py test
after_success:
 - coveralls
